### ISSUE TITLE
Unable to change VPL activity gradebook ID number in Moodle 

### ISSUE THREAD

**Issue by FeldrinH** [jcrodriguez-dis/moodle-mod_vpl#157]
I don't know if this issue is caused by VPL, but it only seems to occur with VPL activities, so I figured this was the most appropriate place to report it for now.

When changing the gradebook ID number of a VPL activity in Moodle (Settings -> Common module settings -> ID number) and then clicking 'Save and display' it returns to the activity overview page as if the saving was successful (and in fact other changed settings are saved successfully), but when opening the settings again the ID number is unchanged from to its original value (which appears to be the activity id shown in the page url).

When doing the same steps with some other type of assignment, the ID number is changed as expected. Only VPL seems to silently reject any changes to the ID number.

It would be nice if this was fixed. Working with automatically assigned numeric ID-s in the gradebook calculations is inconvenient and confusing.

**Comment by jcrodriguez-dis** [comment]
Dear @FeldrinH,

Thank you for bringing this issue to our attention. We appreciate your detailed description of the bug, which has helped us understand the problem more clearly. I am pleased to inform you that the issue you've reported has been resolved in VPL 4.2.2 b56cc3aebe8e8b05dbd75370e54917fe4ff3c6c8.

The core of the issue was a confusion between the course module's `idnumber` and the `id` fields. This had been a longstanding bug in the VPL system, and I acknowledge that the lack of clear documentation contributed to the confusion.

Again, thank you for your contribution to improving VPL. We value your input, and we are committed to ensuring a robust and user-friendly experience.

Best regards,
Juan Carlos.

**Comment by FeldrinH** [comment]
Unfortunately it appears that the bug has been only partially fixed. With VPL 4.2.2 it is now possible to assign a custom ID number to an assignment during initial creation. However, after the assignment has been created it is not possible to change the ID number. When I go to Settings -> Common module settings -> ID number, change the ID number value and press 'Save and display' then it does not show any error but silently ignores the new ID number and uses the previous value instead.
